-- Fullblood case seed INSERT SQL (idempotent)
-- Execute in MySQL 8.0+.
-- Target: recreate one product + one device + two rules (full-model rule + action rule).

SET NAMES utf8mb4;

SET @tenant_id = 1;
SET @creator = '1';
SET @updater = '1';

SET @product_key = 'AUTO_FULLBLOOD_SEED_V1';
SET @product_name = 'AutoFullbloodSeedV1';
SET @device_dn = 'AUTO-FULLBLOOD-SEED-DN-V1';
SET @device_name = 'AutoFullbloodSeedDeviceV1';
SET @serial_no = 'AUTOFULLBLOODSEED000000000000000001';
SET @product_secret = 'fullbloodseedv1secret000000000000';

SET @rule_name_full = 'AUTO_FULLBLOOD_RULE_SEED_V1';
SET @rule_name_action = 'AUTO_ACTION_RULE_SEED_V1';

-- Full thing-model JSON (base64 encoded, decoded at insert time)
SET @model_b64 = 'eyJwcm9wZXJ0aWVzIjpbeyJpZGVudGlmaWVyIjoicF9ib29sIiwiZGF0YVR5cGUiOnsidHlwZSI6ImJvb2wiLCJzcGVjcyI6eyIwIjoib25saW5lIiwiMSI6Im9mZmxpbmUifX0sIm5hbWUiOiJTd2l0Y2hNYXBwZWQiLCJhY2Nlc3NNb2RlIjoicnciLCJkZXNjcmlwdGlvbiI6bnVsbCwidW5pdCI6bnVsbCwiaWNvbklkIjpudWxsLCJpY29uIjpudWxsLCJwcm9EYXRhIjpudWxsfSx7ImlkZW50aWZpZXIiOiJwX2VudW0iLCJkYXRhVHlwZSI6eyJ0eXBlIjoiZW51bSIsInNwZWNzIjp7IjAiOiJhdXRvIiwiMSI6Im1hbnVhbCIsIjIiOiJlY28ifX0sIm5hbWUiOiJNb2RlIiwiYWNjZXNzTW9kZSI6InJ3IiwiZGVzY3JpcHRpb24iOm51bGwsInVuaXQiOm51bGwsImljb25JZCI6bnVsbCwiaWNvbiI6bnVsbCwicHJvRGF0YSI6bnVsbH0seyJpZGVudGlmaWVyIjoicF9pbnQzMiIsImRhdGFUeXBlIjp7InR5cGUiOiJpbnQzMiIsInNwZWNzIjp7Im1pbiI6MCwibWF4IjoyMTQ3NDgzNjQ3fX0sIm5hbWUiOiJDb3VudGVyMzIiLCJhY2Nlc3NNb2RlIjoicnciLCJkZXNjcmlwdGlvbiI6bnVsbCwidW5pdCI6bnVsbCwiaWNvbklkIjpudWxsLCJpY29uIjpudWxsLCJwcm9EYXRhIjpudWxsfSx7ImlkZW50aWZpZXIiOiJwX2ludDY0IiwiZGF0YVR5cGUiOnsidHlwZSI6ImludDY0Iiwic3BlY3MiOnsibWluIjowLCJtYXgiOiI5MjIzMzcyMDM2ODU0Nzc1ODA3In19LCJuYW1lIjoiQ291bnRlcjY0IiwiYWNjZXNzTW9kZSI6InJ3IiwiZGVzY3JpcHRpb24iOm51bGwsInVuaXQiOm51bGwsImljb25JZCI6bnVsbCwiaWNvbiI6bnVsbCwicHJvRGF0YSI6bnVsbH0seyJpZGVudGlmaWVyIjoicF9mbG9hdCIsImRhdGFUeXBlIjp7InR5cGUiOiJmbG9hdCIsInNwZWNzIjp7Im1pbiI6MCwibWF4Ijo5OTk5LCJwcmVjaXNpb24iOjJ9fSwibmFtZSI6IkZsb3dSYXRlIiwiYWNjZXNzTW9kZSI6InJ3IiwiZGVzY3JpcHRpb24iOm51bGwsInVuaXQiOm51bGwsImljb25JZCI6bnVsbCwiaWNvbiI6bnVsbCwicHJvRGF0YSI6bnVsbH0seyJpZGVudGlmaWVyIjoicF9kb3VibGUiLCJkYXRhVHlwZSI6eyJ0eXBlIjoiZG91YmxlIiwic3BlY3MiOnsibWluIjotMTAwLCJtYXgiOjIwMCwicHJlY2lzaW9uIjozfX0sIm5hbWUiOiJUZW1wRG91YmxlIiwiYWNjZXNzTW9kZSI6InJ3IiwiZGVzY3JpcHRpb24iOm51bGwsInVuaXQiOm51bGwsImljb25JZCI6bnVsbCwiaWNvbiI6bnVsbCwicHJvRGF0YSI6bnVsbH0seyJpZGVudGlmaWVyIjoicF9zdHJpbmciLCJkYXRhVHlwZSI6eyJ0eXBlIjoic3RyaW5nIiwic3BlY3MiOnsibGVuZ3RoIjoxMjh9fSwibmFtZSI6IlNob3J0VGV4dCIsImFjY2Vzc01vZGUiOiJydyIsImRlc2NyaXB0aW9uIjpudWxsLCJ1bml0IjpudWxsLCJpY29uSWQiOm51bGwsImljb24iOm51bGwsInByb0RhdGEiOm51bGx9LHsiaWRlbnRpZmllciI6InBfdGV4dCIsImRhdGFUeXBlIjp7InR5cGUiOiJ0ZXh0Iiwic3BlY3MiOnsibGVuZ3RoIjoyMDQ4fX0sIm5hbWUiOiJMb25nVGV4dCIsImFjY2Vzc01vZGUiOiJydyIsImRlc2NyaXB0aW9uIjpudWxsLCJ1bml0IjpudWxsLCJpY29uSWQiOm51bGwsImljb24iOm51bGwsInByb0RhdGEiOm51bGx9LHsiaWRlbnRpZmllciI6InBfZGF0ZSIsImRhdGFUeXBlIjp7InR5cGUiOiJkYXRlIiwic3BlY3MiOnsiZm9ybWF0IjoieXl5eS1NTS1kZCJ9fSwibmFtZSI6Ik9ubHlEYXRlIiwiYWNjZXNzTW9kZSI6InJ3IiwiZGVzY3JpcHRpb24iOm51bGwsInVuaXQiOm51bGwsImljb25JZCI6bnVsbCwiaWNvbiI6bnVsbCwicHJvRGF0YSI6bnVsbH0seyJpZGVudGlmaWVyIjoicF9kYXRldGltZSIsImRhdGFUeXBlIjp7InR5cGUiOiJkYXRldGltZSIsInNwZWNzIjp7ImZvcm1hdCI6Inl5eXktTU0tZGQgSEg6bW06c3MifX0sIm5hbWUiOiJEYXRlVGltZSIsImFjY2Vzc01vZGUiOiJydyIsImRlc2NyaXB0aW9uIjpudWxsLCJ1bml0IjpudWxsLCJpY29uSWQiOm51bGwsImljb24iOm51bGwsInByb0RhdGEiOm51bGx9LHsiaWRlbnRpZmllciI6InBfcG9zaXRpb24iLCJkYXRhVHlwZSI6eyJ0eXBlIjoicG9zaXRpb24iLCJzcGVjcyI6e319LCJuYW1lIjoiUG9zaXRpb24iLCJhY2Nlc3NNb2RlIjoicnciLCJkZXNjcmlwdGlvbiI6bnVsbCwidW5pdCI6bnVsbCwiaWNvbklkIjpudWxsLCJpY29uIjpudWxsLCJwcm9EYXRhIjpudWxsfSx7ImlkZW50aWZpZXIiOiJwX29iamVjdDMiLCJkYXRhVHlwZSI6eyJ0eXBlIjoib2JqZWN0Iiwic3BlY3MiOnsicHJvcGVydGllcyI6W3siaWRlbnRpZmllciI6Im1ldGEiLCJuYW1lIjoiTWV0YSIsImRhdGFUeXBlIjp7InR5cGUiOiJvYmplY3QiLCJzcGVjcyI6eyJwcm9wZXJ0aWVzIjpbeyJpZGVudGlmaWVyIjoidmVyc2lvbiIsIm5hbWUiOiJWZXJzaW9uIiwiZGF0YVR5cGUiOnsidHlwZSI6InN0cmluZyIsInNwZWNzIjp7Imxlbmd0aCI6NjR9fX0seyJpZGVudGlmaWVyIjoiZmxhZ3MiLCJuYW1lIjoiRmxhZ3MiLCJkYXRhVHlwZSI6eyJ0eXBlIjoiYXJyYXkiLCJzcGVjcyI6eyJpdGVtVHlwZSI6eyJ0eXBlIjoic3RyaW5nIiwic3BlY3MiOnsibGVuZ3RoIjo2NH19fX19XX19fSx7ImlkZW50aWZpZXIiOiJyZWFkaW5ncyIsIm5hbWUiOiJSZWFkaW5ncyIsImRhdGFUeXBlIjp7InR5cGUiOiJhcnJheSIsInNwZWNzIjp7Iml0ZW1UeXBlIjp7InR5cGUiOiJvYmplY3QiLCJzcGVjcyI6eyJwcm9wZXJ0aWVzIjpbeyJpZGVudGlmaWVyIjoidHMiLCJuYW1lIjoiVHMiLCJkYXRhVHlwZSI6eyJ0eXBlIjoiZGF0ZXRpbWUiLCJzcGVjcyI6eyJmb3JtYXQiOiJ5eXl5LU1NLWRkIEhIOm1tOnNzIn19fSx7ImlkZW50aWZpZXIiOiJ2YWx1ZSIsIm5hbWUiOiJWYWx1ZSIsImRhdGFUeXBlIjp7InR5cGUiOiJkb3VibGUiLCJzcGVjcyI6eyJtaW4iOjAsIm1heCI6OTk5OTksInByZWNpc2lvbiI6Mn19fV19fX19fV19fSwibmFtZSI6Ik9iamVjdDMiLCJhY2Nlc3NNb2RlIjoicnciLCJkZXNjcmlwdGlvbiI6bnVsbCwidW5pdCI6bnVsbCwiaWNvbklkIjpudWxsLCJpY29uIjpudWxsLCJwcm9EYXRhIjpudWxsfSx7ImlkZW50aWZpZXIiOiJwX2FycmF5MyIsImRhdGFUeXBlIjp7InR5cGUiOiJhcnJheSIsInNwZWNzIjp7Iml0ZW1UeXBlIjp7InR5cGUiOiJvYmplY3QiLCJzcGVjcyI6eyJwcm9wZXJ0aWVzIjpbeyJpZGVudGlmaWVyIjoiYnVja2V0SWQiLCJuYW1lIjoiQnVja2V0SWQiLCJkYXRhVHlwZSI6eyJ0eXBlIjoic3RyaW5nIiwic3BlY3MiOnsibGVuZ3RoIjo2NH19fSx7ImlkZW50aWZpZXIiOiJpdGVtcyIsIm5hbWUiOiJJdGVtcyIsImRhdGFUeXBlIjp7InR5cGUiOiJhcnJheSIsInNwZWNzIjp7Iml0ZW1UeXBlIjp7InR5cGUiOiJvYmplY3QiLCJzcGVjcyI6eyJwcm9wZXJ0aWVzIjpbeyJpZGVudGlmaWVyIjoiayIsIm5hbWUiOiJLIiwiZGF0YVR5cGUiOnsidHlwZSI6InN0cmluZyIsInNwZWNzIjp7Imxlbmd0aCI6MzJ9fX0seyJpZGVudGlmaWVyIjoidiIsIm5hbWUiOiJWIiwiZGF0YVR5cGUiOnsidHlwZSI6ImludDMyIiwic3BlY3MiOnsibWluIjowLCJtYXgiOjk5OTk5fX19XX19fX19XX19fX0sIm5hbWUiOiJBcnJheTMiLCJhY2Nlc3NNb2RlIjoicnciLCJkZXNjcmlwdGlvbiI6bnVsbCwidW5pdCI6bnVsbCwiaWNvbklkIjpudWxsLCJpY29uIjpudWxsLCJwcm9EYXRhIjpudWxsfV0sInNlcnZpY2VzIjpbeyJpZGVudGlmaWVyIjoiY2FsaWJyYXRlIiwiaW5wdXREYXRhIjpbeyJpZGVudGlmaWVyIjoiaW5fYm9vbCIsImRhdGFUeXBlIjp7InR5cGUiOiJib29sIiwic3BlY3MiOnsiMCI6Im9mZiIsIjEiOiJvbiJ9fSwibmFtZSI6IkluQm9vbCIsInJlcXVpcmVkIjp0cnVlLCJkZXNjcmlwdGlvbiI6bnVsbH0seyJpZGVudGlmaWVyIjoiaW5fZW51bSIsImRhdGFUeXBlIjp7InR5cGUiOiJlbnVtIiwic3BlY3MiOnsiMCI6ImF1dG8iLCIxIjoibWFudWFsIiwiMiI6ImVjbyJ9fSwibmFtZSI6IkluRW51bSIsInJlcXVpcmVkIjp0cnVlLCJkZXNjcmlwdGlvbiI6bnVsbH0seyJpZGVudGlmaWVyIjoiaW5faW50MzIiLCJkYXRhVHlwZSI6eyJ0eXBlIjoiaW50MzIiLCJzcGVjcyI6eyJtaW4iOjAsIm1heCI6MjE0NzQ4MzY0N319LCJuYW1lIjoiSW5JbnQzMiIsInJlcXVpcmVkIjp0cnVlLCJkZXNjcmlwdGlvbiI6bnVsbH0seyJpZGVudGlmaWVyIjoiaW5faW50NjQiLCJkYXRhVHlwZSI6eyJ0eXBlIjoiaW50NjQiLCJzcGVjcyI6eyJtaW4iOjAsIm1heCI6IjkyMjMzNzIwMzY4NTQ3NzU4MDcifX0sIm5hbWUiOiJJbkludDY0IiwicmVxdWlyZWQiOnRydWUsImRlc2NyaXB0aW9uIjpudWxsfSx7ImlkZW50aWZpZXIiOiJpbl9mbG9hdCIsImRhdGFUeXBlIjp7InR5cGUiOiJmbG9hdCIsInNwZWNzIjp7Im1pbiI6MCwibWF4Ijo5OTk5OSwicHJlY2lzaW9uIjoyfX0sIm5hbWUiOiJJbkZsb2F0IiwicmVxdWlyZWQiOnRydWUsImRlc2NyaXB0aW9uIjpudWxsfSx7ImlkZW50aWZpZXIiOiJpbl9kb3VibGUiLCJkYXRhVHlwZSI6eyJ0eXBlIjoiZG91YmxlIiwic3BlY3MiOnsibWluIjowLCJtYXgiOjk5OTk5LCJwcmVjaXNpb24iOjN9fSwibmFtZSI6IkluRG91YmxlIiwicmVxdWlyZWQiOnRydWUsImRlc2NyaXB0aW9uIjpudWxsfSx7ImlkZW50aWZpZXIiOiJpbl9zdHJpbmciLCJkYXRhVHlwZSI6eyJ0eXBlIjoic3RyaW5nIiwic3BlY3MiOnsibGVuZ3RoIjoxMjh9fSwibmFtZSI6IkluU3RyaW5nIiwicmVxdWlyZWQiOnRydWUsImRlc2NyaXB0aW9uIjpudWxsfSx7ImlkZW50aWZpZXIiOiJpbl90ZXh0IiwiZGF0YVR5cGUiOnsidHlwZSI6InRleHQiLCJzcGVjcyI6eyJsZW5ndGgiOjIwNDh9fSwibmFtZSI6IkluVGV4dCIsInJlcXVpcmVkIjpmYWxzZSwiZGVzY3JpcHRpb24iOm51bGx9LHsiaWRlbnRpZmllciI6ImluX2RhdGUiLCJkYXRhVHlwZSI6eyJ0eXBlIjoiZGF0ZSIsInNwZWNzIjp7ImZvcm1hdCI6Inl5eXktTU0tZGQifX0sIm5hbWUiOiJJbkRhdGUiLCJyZXF1aXJlZCI6dHJ1ZSwiZGVzY3JpcHRpb24iOm51bGx9LHsiaWRlbnRpZmllciI6ImluX2RhdGV0aW1lIiwiZGF0YVR5cGUiOnsidHlwZSI6ImRhdGV0aW1lIiwic3BlY3MiOnsiZm9ybWF0IjoieXl5eS1NTS1kZCBISDptbTpzcyJ9fSwibmFtZSI6IkluRGF0ZVRpbWUiLCJyZXF1aXJlZCI6dHJ1ZSwiZGVzY3JpcHRpb24iOm51bGx9LHsiaWRlbnRpZmllciI6ImluX3Bvc2l0aW9uIiwiZGF0YVR5cGUiOnsidHlwZSI6InBvc2l0aW9uIiwic3BlY3MiOnt9fSwibmFtZSI6IkluUG9zaXRpb24iLCJyZXF1aXJlZCI6dHJ1ZSwiZGVzY3JpcHRpb24iOm51bGx9LHsiaWRlbnRpZmllciI6ImluX29iamVjdDMiLCJkYXRhVHlwZSI6eyJ0eXBlIjoib2JqZWN0Iiwic3BlY3MiOnsicHJvcGVydGllcyI6W3siaWRlbnRpZmllciI6InZlcnNpb24iLCJuYW1lIjoiVmVyc2lvbiIsImRhdGFUeXBlIjp7InR5cGUiOiJzdHJpbmciLCJzcGVjcyI6eyJsZW5ndGgiOjY0fX19LHsiaWRlbnRpZmllciI6Im1ldHJpY3MiLCJuYW1lIjoiTWV0cmljcyIsImRhdGFUeXBlIjp7InR5cGUiOiJhcnJheSIsInNwZWNzIjp7Iml0ZW1UeXBlIjp7InR5cGUiOiJvYmplY3QiLCJzcGVjcyI6eyJwcm9wZXJ0aWVzIjpbeyJpZGVudGlmaWVyIjoiayIsIm5hbWUiOiJLIiwiZGF0YVR5cGUiOnsidHlwZSI6InN0cmluZyIsInNwZWNzIjp7Imxlbmd0aCI6MzJ9fX0seyJpZGVudGlmaWVyIjoidiIsIm5hbWUiOiJWIiwiZGF0YVR5cGUiOnsidHlwZSI6ImRvdWJsZSIsInNwZWNzIjp7Im1pbiI6MCwibWF4Ijo5OTk5OSwicHJlY2lzaW9uIjoyfX19XX19fX19XX19LCJuYW1lIjoiSW5PYmplY3QzIiwicmVxdWlyZWQiOnRydWUsImRlc2NyaXB0aW9uIjpudWxsfSx7ImlkZW50aWZpZXIiOiJpbl9hcnJheTMiLCJkYXRhVHlwZSI6eyJ0eXBlIjoiYXJyYXkiLCJzcGVjcyI6eyJpdGVtVHlwZSI6eyJ0eXBlIjoib2JqZWN0Iiwic3BlY3MiOnsicHJvcGVydGllcyI6W3siaWRlbnRpZmllciI6ImJ1Y2tldCIsIm5hbWUiOiJCdWNrZXQiLCJkYXRhVHlwZSI6eyJ0eXBlIjoic3RyaW5nIiwic3BlY3MiOnsibGVuZ3RoIjo2NH19fSx7ImlkZW50aWZpZXIiOiJpdGVtcyIsIm5hbWUiOiJJdGVtcyIsImRhdGFUeXBlIjp7InR5cGUiOiJhcnJheSIsInNwZWNzIjp7Iml0ZW1UeXBlIjp7InR5cGUiOiJvYmplY3QiLCJzcGVjcyI6eyJwcm9wZXJ0aWVzIjpbeyJpZGVudGlmaWVyIjoiY29kZSIsIm5hbWUiOiJDb2RlIiwiZGF0YVR5cGUiOnsidHlwZSI6InN0cmluZyIsInNwZWNzIjp7Imxlbmd0aCI6MzJ9fX0seyJpZGVudGlmaWVyIjoidmFsdWUiLCJuYW1lIjoiVmFsdWUiLCJkYXRhVHlwZSI6eyJ0eXBlIjoiaW50MzIiLCJzcGVjcyI6eyJtaW4iOjAsIm1heCI6OTk5OTl9fX1dfX19fX1dfX19fSwibmFtZSI6IkluQXJyYXkzIiwicmVxdWlyZWQiOnRydWUsImRlc2NyaXB0aW9uIjpudWxsfV0sIm91dHB1dERhdGEiOlt7ImlkZW50aWZpZXIiOiJvdXRfYm9vbCIsImRhdGFUeXBlIjp7InR5cGUiOiJib29sIiwic3BlY3MiOnsiMCI6ImZhaWwiLCIxIjoic3VjY2VzcyJ9fSwibmFtZSI6Ik91dEJvb2wiLCJyZXF1aXJlZCI6ZmFsc2UsImRlc2NyaXB0aW9uIjpudWxsfSx7ImlkZW50aWZpZXIiOiJvdXRfZW51bSIsImRhdGFUeXBlIjp7InR5cGUiOiJlbnVtIiwic3BlY3MiOnsiMCI6ImF1dG8iLCIxIjoibWFudWFsIiwiMiI6ImVjbyJ9fSwibmFtZSI6Ik91dEVudW0iLCJyZXF1aXJlZCI6ZmFsc2UsImRlc2NyaXB0aW9uIjpudWxsfSx7ImlkZW50aWZpZXIiOiJvdXRfaW50MzIiLCJkYXRhVHlwZSI6eyJ0eXBlIjoiaW50MzIiLCJzcGVjcyI6eyJtaW4iOjAsIm1heCI6MjE0NzQ4MzY0N319LCJuYW1lIjoiT3V0SW50MzIiLCJyZXF1aXJlZCI6ZmFsc2UsImRlc2NyaXB0aW9uIjpudWxsfSx7ImlkZW50aWZpZXIiOiJvdXRfaW50NjQiLCJkYXRhVHlwZSI6eyJ0eXBlIjoiaW50NjQiLCJzcGVjcyI6eyJtaW4iOjAsIm1heCI6IjkyMjMzNzIwMzY4NTQ3NzU4MDcifX0sIm5hbWUiOiJPdXRJbnQ2NCIsInJlcXVpcmVkIjpmYWxzZSwiZGVzY3JpcHRpb24iOm51bGx9LHsiaWRlbnRpZmllciI6Im91dF9mbG9hdCIsImRhdGFUeXBlIjp7InR5cGUiOiJmbG9hdCIsInNwZWNzIjp7Im1pbiI6MCwibWF4Ijo5OTk5OSwicHJlY2lzaW9uIjoyfX0sIm5hbWUiOiJPdXRGbG9hdCIsInJlcXVpcmVkIjpmYWxzZSwiZGVzY3JpcHRpb24iOm51bGx9LHsiaWRlbnRpZmllciI6Im91dF9kb3VibGUiLCJkYXRhVHlwZSI6eyJ0eXBlIjoiZG91YmxlIiwic3BlY3MiOnsibWluIjowLCJtYXgiOjk5OTk5LCJwcmVjaXNpb24iOjN9fSwibmFtZSI6Ik91dERvdWJsZSIsInJlcXVpcmVkIjpmYWxzZSwiZGVzY3JpcHRpb24iOm51bGx9LHsiaWRlbnRpZmllciI6Im91dF9zdHJpbmciLCJkYXRhVHlwZSI6eyJ0eXBlIjoic3RyaW5nIiwic3BlY3MiOnsibGVuZ3RoIjoxMjh9fSwibmFtZSI6Ik91dFN0cmluZyIsInJlcXVpcmVkIjpmYWxzZSwiZGVzY3JpcHRpb24iOm51bGx9LHsiaWRlbnRpZmllciI6Im91dF90ZXh0IiwiZGF0YVR5cGUiOnsidHlwZSI6InRleHQiLCJzcGVjcyI6eyJsZW5ndGgiOjIwNDh9fSwibmFtZSI6Ik91dFRleHQiLCJyZXF1aXJlZCI6ZmFsc2UsImRlc2NyaXB0aW9uIjpudWxsfSx7ImlkZW50aWZpZXIiOiJvdXRfZGF0ZSIsImRhdGFUeXBlIjp7InR5cGUiOiJkYXRlIiwic3BlY3MiOnsiZm9ybWF0IjoieXl5eS1NTS1kZCJ9fSwibmFtZSI6Ik91dERhdGUiLCJyZXF1aXJlZCI6ZmFsc2UsImRlc2NyaXB0aW9uIjpudWxsfSx7ImlkZW50aWZpZXIiOiJvdXRfZGF0ZXRpbWUiLCJkYXRhVHlwZSI6eyJ0eXBlIjoiZGF0ZXRpbWUiLCJzcGVjcyI6eyJmb3JtYXQiOiJ5eXl5LU1NLWRkIEhIOm1tOnNzIn19LCJuYW1lIjoiT3V0RGF0ZVRpbWUiLCJyZXF1aXJlZCI6ZmFsc2UsImRlc2NyaXB0aW9uIjpudWxsfSx7ImlkZW50aWZpZXIiOiJvdXRfcG9zaXRpb24iLCJkYXRhVHlwZSI6eyJ0eXBlIjoicG9zaXRpb24iLCJzcGVjcyI6e319LCJuYW1lIjoiT3V0UG9zaXRpb24iLCJyZXF1aXJlZCI6ZmFsc2UsImRlc2NyaXB0aW9uIjpudWxsfSx7ImlkZW50aWZpZXIiOiJvdXRfb2JqZWN0MyIsImRhdGFUeXBlIjp7InR5cGUiOiJvYmplY3QiLCJzcGVjcyI6eyJwcm9wZXJ0aWVzIjpbeyJpZGVudGlmaWVyIjoiYmF0Y2giLCJuYW1lIjoiQmF0Y2giLCJkYXRhVHlwZSI6eyJ0eXBlIjoic3RyaW5nIiwic3BlY3MiOnsibGVuZ3RoIjo2NH19fSx7ImlkZW50aWZpZXIiOiJzY29yZSIsIm5hbWUiOiJTY29yZSIsImRhdGFUeXBlIjp7InR5cGUiOiJkb3VibGUiLCJzcGVjcyI6eyJtaW4iOjAsIm1heCI6MTAwLCJwcmVjaXNpb24iOjJ9fX0seyJpZGVudGlmaWVyIjoib2siLCJuYW1lIjoiT2siLCJkYXRhVHlwZSI6eyJ0eXBlIjoiYm9vbCIsInNwZWNzIjp7IjAiOiJubyIsIjEiOiJ5ZXMifX19XX19LCJuYW1lIjoiT3V0T2JqZWN0MyIsInJlcXVpcmVkIjpmYWxzZSwiZGVzY3JpcHRpb24iOm51bGx9LHsiaWRlbnRpZmllciI6Im91dF9hcnJheTMiLCJkYXRhVHlwZSI6eyJ0eXBlIjoiYXJyYXkiLCJzcGVjcyI6eyJpdGVtVHlwZSI6eyJ0eXBlIjoib2JqZWN0Iiwic3BlY3MiOnsicHJvcGVydGllcyI6W3siaWRlbnRpZmllciI6Imdyb3VwIiwibmFtZSI6Ikdyb3VwIiwiZGF0YVR5cGUiOnsidHlwZSI6InN0cmluZyIsInNwZWNzIjp7Imxlbmd0aCI6NjR9fX0seyJpZGVudGlmaWVyIjoiY291bnQiLCJuYW1lIjoiQ291bnQiLCJkYXRhVHlwZSI6eyJ0eXBlIjoiaW50MzIiLCJzcGVjcyI6eyJtaW4iOjAsIm1heCI6OTk5OTl9fX1dfX19fSwibmFtZSI6Ik91dEFycmF5MyIsInJlcXVpcmVkIjpmYWxzZSwiZGVzY3JpcHRpb24iOm51bGx9XSwibmFtZSI6IkNhbGlicmF0ZSIsImRlc2NyaXB0aW9uIjoiY2FsaWJyYXRlIHdpdGggYWxsIGRhdGEgdHlwZXMifV0sImV2ZW50cyI6W3siaWRlbnRpZmllciI6ImFsYXJtIiwib3V0cHV0RGF0YSI6W3siaWRlbnRpZmllciI6ImVfYm9vbCIsImRhdGFUeXBlIjp7InR5cGUiOiJib29sIiwic3BlY3MiOnsiMCI6Im5vIiwiMSI6InllcyJ9fSwibmFtZSI6IkVCb29sIiwicmVxdWlyZWQiOmZhbHNlLCJkZXNjcmlwdGlvbiI6bnVsbH0seyJpZGVudGlmaWVyIjoiZV9lbnVtIiwiZGF0YVR5cGUiOnsidHlwZSI6ImVudW0iLCJzcGVjcyI6eyIwIjoiYXV0byIsIjEiOiJtYW51YWwiLCIyIjoiZWNvIn19LCJuYW1lIjoiRUVudW0iLCJyZXF1aXJlZCI6ZmFsc2UsImRlc2NyaXB0aW9uIjpudWxsfSx7ImlkZW50aWZpZXIiOiJlX2ludDMyIiwiZGF0YVR5cGUiOnsidHlwZSI6ImludDMyIiwic3BlY3MiOnsibWluIjowLCJtYXgiOjIxNDc0ODM2NDd9fSwibmFtZSI6IkVJbnQzMiIsInJlcXVpcmVkIjpmYWxzZSwiZGVzY3JpcHRpb24iOm51bGx9LHsiaWRlbnRpZmllciI6ImVfaW50NjQiLCJkYXRhVHlwZSI6eyJ0eXBlIjoiaW50NjQiLCJzcGVjcyI6eyJtaW4iOjAsIm1heCI6IjkyMjMzNzIwMzY4NTQ3NzU4MDcifX0sIm5hbWUiOiJFSW50NjQiLCJyZXF1aXJlZCI6ZmFsc2UsImRlc2NyaXB0aW9uIjpudWxsfSx7ImlkZW50aWZpZXIiOiJlX2Zsb2F0IiwiZGF0YVR5cGUiOnsidHlwZSI6ImZsb2F0Iiwic3BlY3MiOnsibWluIjowLCJtYXgiOjk5OTk5LCJwcmVjaXNpb24iOjJ9fSwibmFtZSI6IkVGbG9hdCIsInJlcXVpcmVkIjpmYWxzZSwiZGVzY3JpcHRpb24iOm51bGx9LHsiaWRlbnRpZmllciI6ImVfZG91YmxlIiwiZGF0YVR5cGUiOnsidHlwZSI6ImRvdWJsZSIsInNwZWNzIjp7Im1pbiI6MCwibWF4Ijo5OTk5OSwicHJlY2lzaW9uIjozfX0sIm5hbWUiOiJFRG91YmxlIiwicmVxdWlyZWQiOmZhbHNlLCJkZXNjcmlwdGlvbiI6bnVsbH0seyJpZGVudGlmaWVyIjoiZV9zdHJpbmciLCJkYXRhVHlwZSI6eyJ0eXBlIjoic3RyaW5nIiwic3BlY3MiOnsibGVuZ3RoIjoxMjh9fSwibmFtZSI6IkVTdHJpbmciLCJyZXF1aXJlZCI6ZmFsc2UsImRlc2NyaXB0aW9uIjpudWxsfSx7ImlkZW50aWZpZXIiOiJlX3RleHQiLCJkYXRhVHlwZSI6eyJ0eXBlIjoidGV4dCIsInNwZWNzIjp7Imxlbmd0aCI6MjA0OH19LCJuYW1lIjoiRVRleHQiLCJyZXF1aXJlZCI6ZmFsc2UsImRlc2NyaXB0aW9uIjpudWxsfSx7ImlkZW50aWZpZXIiOiJlX2RhdGUiLCJkYXRhVHlwZSI6eyJ0eXBlIjoiZGF0ZSIsInNwZWNzIjp7ImZvcm1hdCI6Inl5eXktTU0tZGQifX0sIm5hbWUiOiJFRGF0ZSIsInJlcXVpcmVkIjpmYWxzZSwiZGVzY3JpcHRpb24iOm51bGx9LHsiaWRlbnRpZmllciI6ImVfZGF0ZXRpbWUiLCJkYXRhVHlwZSI6eyJ0eXBlIjoiZGF0ZXRpbWUiLCJzcGVjcyI6eyJmb3JtYXQiOiJ5eXl5LU1NLWRkIEhIOm1tOnNzIn19LCJuYW1lIjoiRURhdGVUaW1lIiwicmVxdWlyZWQiOmZhbHNlLCJkZXNjcmlwdGlvbiI6bnVsbH0seyJpZGVudGlmaWVyIjoiZV9wb3NpdGlvbiIsImRhdGFUeXBlIjp7InR5cGUiOiJwb3NpdGlvbiIsInNwZWNzIjp7fX0sIm5hbWUiOiJFUG9zaXRpb24iLCJyZXF1aXJlZCI6ZmFsc2UsImRlc2NyaXB0aW9uIjpudWxsfSx7ImlkZW50aWZpZXIiOiJlX29iamVjdDMiLCJkYXRhVHlwZSI6eyJ0eXBlIjoib2JqZWN0Iiwic3BlY3MiOnsicHJvcGVydGllcyI6W3siaWRlbnRpZmllciI6ImhlYWRlcnMiLCJuYW1lIjoiSGVhZGVycyIsImRhdGFUeXBlIjp7InR5cGUiOiJvYmplY3QiLCJzcGVjcyI6eyJwcm9wZXJ0aWVzIjpbeyJpZGVudGlmaWVyIjoic291cmNlIiwibmFtZSI6IlNvdXJjZSIsImRhdGFUeXBlIjp7InR5cGUiOiJzdHJpbmciLCJzcGVjcyI6eyJsZW5ndGgiOjY0fX19LHsiaWRlbnRpZmllciI6ImxldmVsIiwibmFtZSI6IkxldmVsIiwiZGF0YVR5cGUiOnsidHlwZSI6InN0cmluZyIsInNwZWNzIjp7Imxlbmd0aCI6MzJ9fX1dfX19LHsiaWRlbnRpZmllciI6InJlY29yZHMiLCJuYW1lIjoiUmVjb3JkcyIsImRhdGFUeXBlIjp7InR5cGUiOiJhcnJheSIsInNwZWNzIjp7Iml0ZW1UeXBlIjp7InR5cGUiOiJvYmplY3QiLCJzcGVjcyI6eyJwcm9wZXJ0aWVzIjpbeyJpZGVudGlmaWVyIjoiY29kZSIsIm5hbWUiOiJDb2RlIiwiZGF0YVR5cGUiOnsidHlwZSI6InN0cmluZyIsInNwZWNzIjp7Imxlbmd0aCI6NjR9fX0seyJpZGVudGlmaWVyIjoibWVzc2FnZSIsIm5hbWUiOiJNZXNzYWdlIiwiZGF0YVR5cGUiOnsidHlwZSI6InRleHQiLCJzcGVjcyI6eyJsZW5ndGgiOjUxMn19fV19fX19fV19fSwibmFtZSI6IkVPYmplY3QzIiwicmVxdWlyZWQiOmZhbHNlLCJkZXNjcmlwdGlvbiI6bnVsbH0seyJpZGVudGlmaWVyIjoiZV9hcnJheTMiLCJkYXRhVHlwZSI6eyJ0eXBlIjoiYXJyYXkiLCJzcGVjcyI6eyJpdGVtVHlwZSI6eyJ0eXBlIjoib2JqZWN0Iiwic3BlY3MiOnsicHJvcGVydGllcyI6W3siaWRlbnRpZmllciI6ImJ1Y2tldElkIiwibmFtZSI6IkJ1Y2tldElkIiwiZGF0YVR5cGUiOnsidHlwZSI6InN0cmluZyIsInNwZWNzIjp7Imxlbmd0aCI6NjR9fX0seyJpZGVudGlmaWVyIjoiaXRlbXMiLCJuYW1lIjoiSXRlbXMiLCJkYXRhVHlwZSI6eyJ0eXBlIjoiYXJyYXkiLCJzcGVjcyI6eyJpdGVtVHlwZSI6eyJ0eXBlIjoib2JqZWN0Iiwic3BlY3MiOnsicHJvcGVydGllcyI6W3siaWRlbnRpZmllciI6ImsiLCJuYW1lIjoiSyIsImRhdGFUeXBlIjp7InR5cGUiOiJzdHJpbmciLCJzcGVjcyI6eyJsZW5ndGgiOjMyfX19LHsiaWRlbnRpZmllciI6InYiLCJuYW1lIjoiViIsImRhdGFUeXBlIjp7InR5cGUiOiJkb3VibGUiLCJzcGVjcyI6eyJtaW4iOjAsIm1heCI6OTk5OTksInByZWNpc2lvbiI6Mn19fV19fX19fV19fX19LCJuYW1lIjoiRUFycmF5MyIsInJlcXVpcmVkIjpmYWxzZSwiZGVzY3JpcHRpb24iOm51bGx9XSwibmFtZSI6IkFsYXJtIiwiZGVzY3JpcHRpb24iOiJhbGFybSB3aXRoIGFsbCBkYXRhIHR5cGVzIn1dfQ==';

-- Rule configs (base64 encoded)
SET @r34_listeners_b64 = 'eyJ0eXBlIjoiZGV2aWNlIiwiY29uZmlnIjoie1widHlwZVwiOlwiZGV2aWNlXCIsXCJwa1wiOlwiQVVUT19GVUxMQkxPT0RfMTc3Njg2NDMyMjcwMVwiLFwiZG5cIjpcIkFVVE8tRlVMTEJMT09ELUROLTE3NzY4NjQzMjI3MDFcIixcImNvbmRcIjoxLFwiY29uZGl0aW9uc1wiOlt7XCJpZGVudGlmaWVyXCI6XCJyZXBvcnRcIixcInR5cGVcIjpcInByb3BlcnR5XCIsXCJwYXJhbWV0ZXJzXCI6W3tcImlkZW50aWZpZXJcIjpcIipcIixcImNvbXBhcmF0b3JcIjpcIipcIixcInZhbHVlXCI6XCIqXCJ9XX0se1wiaWRlbnRpZmllclwiOlwiZXZlbnQ6KlwiLFwidHlwZVwiOlwiZXZlbnRcIixcInBhcmFtZXRlcnNcIjpbXX0se1wiaWRlbnRpZmllclwiOlwic2VydmljZV9yZXBseToqXCIsXCJ0eXBlXCI6XCJzZXJ2aWNlX3JlcGx5XCIsXCJwYXJhbWV0ZXJzXCI6W119XX0ifQ==';
SET @r34_filters_b64 = 'eyJ0eXBlIjoiZGV2aWNlIiwiY29uZmlnIjoie1widHlwZVwiOlwiZGV2aWNlXCIsXCJwa1wiOlwiQVVUT19GVUxMQkxPT0RfMTc3Njg2NDMyMjcwMVwiLFwiZG5cIjpcIkFVVE8tRlVMTEJMT09ELUROLTE3NzY4NjQzMjI3MDFcIixcImNvbmRcIjoyLFwiY29uZGl0aW9uc1wiOlt7XCJ0eXBlXCI6XCJwcm9wZXJ0eVwiLFwiaWRlbnRpZmllclwiOlwicF9ib29sXCIsXCJjb21wYXJhdG9yXCI6XCI9PVwiLFwidmFsdWVcIjpcIjFcIn0se1widHlwZVwiOlwicHJvcGVydHlcIixcImlkZW50aWZpZXJcIjpcInBfZW51bVwiLFwiY29tcGFyYXRvclwiOlwiPT1cIixcInZhbHVlXCI6XCIyXCJ9LHtcInR5cGVcIjpcInByb3BlcnR5XCIsXCJpZGVudGlmaWVyXCI6XCJwX2ludDMyXCIsXCJjb21wYXJhdG9yXCI6XCJcdTAwM2VcIixcInZhbHVlXCI6XCIxMDBcIn0se1widHlwZVwiOlwicHJvcGVydHlcIixcImlkZW50aWZpZXJcIjpcInBfaW50NjRcIixcImNvbXBhcmF0b3JcIjpcIlx1MDAzZVwiLFwidmFsdWVcIjpcIjEwMDAwMFwifSx7XCJ0eXBlXCI6XCJwcm9wZXJ0eVwiLFwiaWRlbnRpZmllclwiOlwicF9mbG9hdFwiLFwiY29tcGFyYXRvclwiOlwiXHUwMDNlXCIsXCJ2YWx1ZVwiOlwiMS4xXCJ9LHtcInR5cGVcIjpcInByb3BlcnR5XCIsXCJpZGVudGlmaWVyXCI6XCJwX2RvdWJsZVwiLFwiY29tcGFyYXRvclwiOlwiXHUwMDNlXCIsXCJ2YWx1ZVwiOlwiMi4yXCJ9LHtcInR5cGVcIjpcInByb3BlcnR5XCIsXCJpZGVudGlmaWVyXCI6XCJwX3N0cmluZ1wiLFwiY29tcGFyYXRvclwiOlwiY29udGFpblwiLFwidmFsdWVcIjpcInNob3J0XCJ9LHtcInR5cGVcIjpcInByb3BlcnR5XCIsXCJpZGVudGlmaWVyXCI6XCJwX3RleHRcIixcImNvbXBhcmF0b3JcIjpcImNvbnRhaW5cIixcInZhbHVlXCI6XCJmdWxsYmxvb2RcIn0se1widHlwZVwiOlwicHJvcGVydHlcIixcImlkZW50aWZpZXJcIjpcInBfZGF0ZVwiLFwiY29tcGFyYXRvclwiOlwiPT1cIixcInZhbHVlXCI6XCIyMDI2LTA0LTIyXCJ9LHtcInR5cGVcIjpcInByb3BlcnR5XCIsXCJpZGVudGlmaWVyXCI6XCJwX2RhdGV0aW1lXCIsXCJjb21wYXJhdG9yXCI6XCJjb250YWluXCIsXCJ2YWx1ZVwiOlwiMjAyNi0wNC0yMlwifSx7XCJ0eXBlXCI6XCJwcm9wZXJ0eVwiLFwiaWRlbnRpZmllclwiOlwicF9wb3NpdGlvblwiLFwiY29tcGFyYXRvclwiOlwiY29udGFpblwiLFwidmFsdWVcIjpcIjMxLjIzMDRcIn0se1widHlwZVwiOlwicHJvcGVydHlcIixcImlkZW50aWZpZXJcIjpcInBfb2JqZWN0My5tZXRhLnZlcnNpb25cIixcImNvbXBhcmF0b3JcIjpcIj09XCIsXCJ2YWx1ZVwiOlwidjNcIn0se1widHlwZVwiOlwicHJvcGVydHlcIixcImlkZW50aWZpZXJcIjpcInBfb2JqZWN0My5tZXRhLmZsYWdzWypdXCIsXCJjb21wYXJhdG9yXCI6XCJjb250YWluXCIsXCJ2YWx1ZVwiOlwiZjFcIn0se1widHlwZVwiOlwicHJvcGVydHlcIixcImlkZW50aWZpZXJcIjpcInBfYXJyYXkzWypdLmJ1Y2tldElkXCIsXCJjb21wYXJhdG9yXCI6XCJjb250YWluXCIsXCJ2YWx1ZVwiOlwiYjAwMVwifSx7XCJ0eXBlXCI6XCJwcm9wZXJ0eVwiLFwiaWRlbnRpZmllclwiOlwicF9hcnJheTNbKl0uaXRlbXNbKl0ua1wiLFwiY29tcGFyYXRvclwiOlwiPT1cIixcInZhbHVlXCI6XCJhXCJ9XX0ifQ==';
SET @r34_actions_b64 = 'W10='; -- []
SET @r34_trigger_b64 = 'eyJtaW5JbnRlcnZhbFNlYyI6MCwiZGVsYXlTZWMiOjAsImVuYWJsZUFsZXJ0UmVjb3ZlciI6ZmFsc2UsInJlY292ZXJRdWlldFNlYyI6MH0=';

SET @r36_listeners_b64 = 'eyJ0eXBlIjoiZGV2aWNlIiwiY29uZmlnIjoie1wiY29uZFwiOjEsXCJwa1wiOlwiQVVUT19GVUxMQkxPT0RfMTc3Njg2NDMyMjcwMVwiLFwiY29uZGl0aW9uc1wiOlt7XCJ0eXBlXCI6XCJwcm9wZXJ0eVwiLFwiaWRlbnRpZmllclwiOlwicmVwb3J0XCIsXCJwYXJhbWV0ZXJzXCI6W3tcImNvbXBhcmF0b3JcIjpcIipcIixcInZhbHVlXCI6XCIqXCIsXCJpZGVudGlmaWVyXCI6XCIqXCJ9XX1dLFwidHlwZVwiOlwiZGV2aWNlXCIsXCJkblwiOlwiQVVUTy1GVUxMQkxPT0QtRE4tMTc3Njg2NDMyMjcwMVwifSJ9';
SET @r36_filters_b64 = 'eyJ0eXBlIjoiZGV2aWNlIiwiY29uZmlnIjoie1wiY29uZFwiOjIsXCJwa1wiOlwiQVVUT19GVUxMQkxPT0RfMTc3Njg2NDMyMjcwMVwiLFwiY29uZGl0aW9uc1wiOlt7XCJjb21wYXJhdG9yXCI6XCI9PVwiLFwiaWRlbnRpZmllclwiOlwicF9ib29sXCIsXCJ2YWx1ZVwiOlwiMVwiLFwidHlwZVwiOlwicHJvcGVydHlcIn1dLFwidHlwZVwiOlwiZGV2aWNlXCIsXCJkblwiOlwiQVVUTy1GVUxMQkxPT0QtRE4tMTc3Njg2NDMyMjcwMVwifSJ9';
SET @r36_actions_b64 = 'eyJ0eXBlIjoiZGV2aWNlIiwiY29uZmlnIjoie1wic2VydmljZXNcIjpbe1wiaW5wdXREYXRhXCI6W3tcImlkZW50aWZpZXJcIjpcInBfdGV4dFwiLFwidmFsdWVcIjpcInJ1bGUtYWN0aW9uLTE3NzY4Njc0Mjc1MTJcIn0se1wiaWRlbnRpZmllclwiOlwicF9ib29sXCIsXCJ2YWx1ZVwiOlwiMVwifV0sXCJpZGVudGlmaWVyXCI6XCJzZXRcIixcImRldmljZVwiOlwiQVVUT19GVUxMQkxPT0RfMTc3Njg2NDMyMjcwMS9BVVRPLUZVTExCTE9PRC1ETi0xNzc2ODY0MzIyNzAxXCJ9XSxcInR5cGVcIjpcImRldmljZVwifSJ9';
SET @r36_trigger_b64 = 'eyJtaW5JbnRlcnZhbFNlYyI6MCwiZGVsYXlTZWMiOjAsImVuYWJsZUFsZXJ0UmVjb3ZlciI6ZmFsc2UsInJlY292ZXJRdWlldFNlYyI6MH0=';

SET @now = NOW();
SET @category_id = (
  SELECT id FROM eiot_category
  WHERE tenant_id = @tenant_id AND deleted = b'0'
  ORDER BY id LIMIT 1
);
SET @category_id = IFNULL(@category_id, 1);

-- Clean old seeded data
DELETE FROM eiot_rule_info
WHERE tenant_id = @tenant_id AND deleted = b'0'
  AND name IN (@rule_name_full, @rule_name_action);

DELETE FROM eiot_device_info
WHERE tenant_id = @tenant_id AND deleted = b'0'
  AND product_key = @product_key
  AND dn = @device_dn;

DELETE FROM eiot_thing_model
WHERE tenant_id = @tenant_id AND deleted = b'0'
  AND product_key = @product_key;

DELETE FROM eiot_product
WHERE tenant_id = @tenant_id AND deleted = b'0'
  AND product_key = @product_key;

-- Insert product
INSERT INTO eiot_product (
  name, category_id, product_key, mcu_code, remark1, img_url, remark, status,
  creator, create_time, updater, update_time, deleted, tenant_id,
  node_type, protocol_code, keep_alive_time, product_secret, transparent, locate_type
) VALUES (
  @product_name, @category_id, @product_key, '',
  'fullblood seed product (all data types)',
  '', 'seeded by fullblood-case-seed-insert.sql', 0,
  @creator, @now, @updater, @now, b'0', @tenant_id,
  0, 'GB28181', 120, @product_secret, b'0', 0
);

-- Insert thing model
INSERT INTO eiot_thing_model (
  creator, create_time, updater, update_time, deleted, tenant_id, product_key, model
) VALUES (
  @creator, @now, @updater, @now, b'0', @tenant_id, @product_key,
  CONVERT(FROM_BASE64(@model_b64) USING utf8mb4)
);

-- Insert device
INSERT INTO eiot_device_info (
  dn, product_key, dept_id, properties, creator, create_time, updater, update_time,
  deleted, tenant_id, name, state, offline_time, online_time, serial_no, remark,
  lat, lon, model, parent_id, active_time, secret, firm_version, addr, transparent, node_type
) VALUES (
  @device_dn, @product_key, 0, NULL, @creator, @now, @updater, @now,
  b'0', @tenant_id, @device_name, 0, NULL, NULL, @serial_no, NULL,
  NULL, NULL, 'M1', NULL, NULL, NULL, '1.0.0', NULL, b'0', 0
);

-- Insert rule #1: full-model match
INSERT INTO eiot_rule_info (
  name, listeners, filters, actions, trigger_options, typ, state, remark,
  creator, create_time, updater, update_time, deleted, tenant_id, dept_id
) VALUES (
  @rule_name_full,
  CONVERT(FROM_BASE64(@r34_listeners_b64) USING utf8mb4),
  CONVERT(FROM_BASE64(@r34_filters_b64) USING utf8mb4),
  CONVERT(FROM_BASE64(@r34_actions_b64) USING utf8mb4),
  CONVERT(FROM_BASE64(@r34_trigger_b64) USING utf8mb4),
  'scene', 1, 'fullblood all-types rule',
  @creator, @now, @updater, @now, b'0', @tenant_id, 0
);

-- Insert rule #2: action trigger
INSERT INTO eiot_rule_info (
  name, listeners, filters, actions, trigger_options, typ, state, remark,
  creator, create_time, updater, update_time, deleted, tenant_id, dept_id
) VALUES (
  @rule_name_action,
  CONVERT(FROM_BASE64(@r36_listeners_b64) USING utf8mb4),
  CONVERT(FROM_BASE64(@r36_filters_b64) USING utf8mb4),
  CONVERT(FROM_BASE64(@r36_actions_b64) USING utf8mb4),
  CONVERT(FROM_BASE64(@r36_trigger_b64) USING utf8mb4),
  'scene', 1, 'fullblood action rule',
  @creator, @now, @updater, @now, b'0', @tenant_id, 0
);

-- Result check
SELECT id, name, product_key, protocol_code, keep_alive_time
FROM eiot_product WHERE product_key = @product_key AND tenant_id = @tenant_id AND deleted = b'0';

SELECT id, product_key, LEFT(model, 120) AS model_preview
FROM eiot_thing_model WHERE product_key = @product_key AND tenant_id = @tenant_id AND deleted = b'0';

SELECT id, dn, product_key, state, serial_no
FROM eiot_device_info WHERE product_key = @product_key AND dn = @device_dn AND tenant_id = @tenant_id AND deleted = b'0';

SELECT id, name, typ, state
FROM eiot_rule_info
WHERE name IN (@rule_name_full, @rule_name_action)
  AND tenant_id = @tenant_id AND deleted = b'0'
ORDER BY id;

